# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: default
type: Opaque
data:
    user: dmlhZGFv
    database: d3AtbHV4
    password: MWYyZDFlMmU2N2Rm
---

